-- IntelliScan Application Database Schema for Supabase
-- version 1.1 - Enhanced for Vehicle Management

-- 1. PROFILES TABLE
-- This table stores public user data. It is linked to the auth.users table.
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- Helper function to create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (new.id, new.raw_user_meta_data->>'username');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the helper function on new user creation
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- RLS policies for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile."
  ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile."
  ON public.profiles FOR UPDATE USING (auth.uid() = id);


-- 2. VEHICLES TABLE
-- Stores information about user's vehicles.
CREATE TABLE public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INT NOT NULL,
  vin TEXT UNIQUE,
  nickname TEXT,
  mileage INT,
  engine_size TEXT,
  fuel_type TEXT,
  transmission TEXT,
  color TEXT,
  license_plate TEXT,
  purchase_date DATE,
  purchase_price DECIMAL(12, 2),
  notes TEXT
);

-- RLS policies for vehicles
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own vehicles."
  ON public.vehicles FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can add new vehicles."
  ON public.vehicles FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own vehicles."
  ON public.vehicles FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own vehicles."
  ON public.vehicles FOR DELETE USING (auth.uid() = user_id);


-- 3. MAINTENANCE RECORDS TABLE
-- Stores maintenance history for each vehicle.
CREATE TABLE public.maintenance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
  service_type TEXT NOT NULL,
  service_date DATE NOT NULL,
  cost DECIMAL(10, 2),
  notes TEXT,
  garage_id BIGINT REFERENCES public.garages(id) ON DELETE SET NULL,
  service_provider TEXT,
  mileage_at_service INT
);

-- RLS policies for maintenance_records
ALTER TABLE public.maintenance_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage records for their own vehicles."
  ON public.maintenance_records FOR ALL
  USING (
    auth.uid() = (
      SELECT user_id FROM public.vehicles WHERE id = vehicle_id
    )
  );


-- 4. REPAIR RECORDS TABLE
-- Stores repair history for each vehicle.
CREATE TABLE public.repair_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
  repair_type TEXT NOT NULL,
  repair_date DATE NOT NULL,
  cost DECIMAL(10, 2),
  notes TEXT,
  garage_id BIGINT REFERENCES public.garages(id) ON DELETE SET NULL,
  service_provider TEXT,
  mileage_at_repair INT,
  status TEXT DEFAULT 'completed' -- 'completed', 'in_progress', 'scheduled'
);

-- RLS policies for repair_records
ALTER TABLE public.repair_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage repair records for their own vehicles."
  ON public.repair_records FOR ALL
  USING (
    auth.uid() = (
      SELECT user_id FROM public.vehicles WHERE id = vehicle_id
    )
  );


-- 5. MAINTENANCE PLANS TABLE
-- Stores planned maintenance schedules for vehicles.
CREATE TABLE public.maintenance_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
  plan_name TEXT NOT NULL,
  service_type TEXT NOT NULL,
  frequency_type TEXT NOT NULL, -- 'mileage', 'days', 'months'
  frequency_value INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- RLS policies for maintenance_plans
ALTER TABLE public.maintenance_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage maintenance plans for their own vehicles."
  ON public.maintenance_plans FOR ALL
  USING (
    auth.uid() = (
      SELECT user_id FROM public.vehicles WHERE id = vehicle_id
    )
  );


-- 6. MAINTENANCE SCHEDULES TABLE
-- Stores scheduled maintenance events.
CREATE TABLE public.maintenance_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
  plan_id BIGINT REFERENCES public.maintenance_plans(id) ON DELETE SET NULL,
  scheduled_date DATE NOT NULL,
  service_type TEXT NOT NULL,
  status TEXT DEFAULT 'scheduled', -- 'scheduled', 'completed', 'missed'
  notes TEXT,
  garage_id BIGINT REFERENCES public.garages(id) ON DELETE SET NULL,
  service_provider TEXT,
  mileage_at_schedule INT,
  completed_at TIMESTAMPTZ
);

-- RLS policies for maintenance_schedules
ALTER TABLE public.maintenance_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage schedules for their own vehicles."
  ON public.maintenance_schedules FOR ALL
  USING (
    auth.uid() = (
      SELECT user_id FROM public.vehicles WHERE id = vehicle_id
    )
  );


-- 7. DIAGNOSTIC REPORTS TABLE
-- Stores results from vehicle diagnostic scans.
CREATE TABLE public.diagnostic_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  report_date DATE NOT NULL,
  status TEXT, -- e.g., 'Good', 'Warning', 'Critical'
  report_data JSONB, -- To store complex diagnostic data, codes, etc.
  notes TEXT
);

-- RLS policies for diagnostic_reports
ALTER TABLE public.diagnostic_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage reports for their own vehicles."
  ON public.diagnostic_reports FOR ALL
  USING (
    auth.uid() = (
      SELECT user_id FROM public.vehicles WHERE id = vehicle_id
    )
  );


-- 8. GARAGES TABLE
-- Stores a user's list of preferred garages.
CREATE TABLE public.garages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  address TEXT,
  phone_number TEXT,
  website TEXT,
  notes TEXT,
  rating DECIMAL(3, 2),
  specialties TEXT[] -- e.g., ['oil_change', 'brake_repair', 'engine_repair']
);

-- RLS policies for garages
ALTER TABLE public.garages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own list of garages."
  ON public.garages FOR ALL USING (auth.uid() = user_id);


-- 9. NOTIFICATIONS TABLE
-- Stores user notification preferences.
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  email_notifications BOOLEAN DEFAULT true,
  push_notifications BOOLEAN DEFAULT true,
  maintenance_reminders BOOLEAN DEFAULT true,
  diagnostic_alerts BOOLEAN DEFAULT true,
  UNIQUE(user_id)
);

-- RLS policies for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own notification preferences."
  ON public.notifications FOR ALL USING (auth.uid() = user_id);

-- Helper function to create notification preferences when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user_notification_prefs()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.notifications (user_id)
  VALUES (new.id);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the helper function on new user creation
CREATE TRIGGER on_auth_user_created_notification_prefs
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_notification_prefs();
